import type { Metadata } from "next";
import { Sora } from "@next/font/google";

import "./globals.css";
import ThemeProvider from "@/components/utils/ThemeProvider";

const sora = Sora({
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cryptpay website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${sora.className} bg-[#0C0D1D]`}>
        <ThemeProvider />
        {children}
      </body>
    </html>
  );
}
